name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gjs gnome-shell xvfb libgtk-4-dev libadwaita-1-dev
    
    - name: Run Tests
      run: ./tests/run_tests_shell.sh
